UNSEEN_CLASSES = {
    "sketchy_1": [
        "cup",
        "swan",
        "harp",
        "squirrel",
        "snail",
        "ray",
        "pineapple",
        "volcano",
        "rifle",
        "scissors",
        "parrot",
        "windmill",
        "teddy_bear",
        "tree",
        "wine_bottle",
        "deer",
        "chicken",
        "hotdog",
        "wheelchair",
        "tank",
        "umbrella",
        "butterfly",
        "camel",
        "horse",
        "bell"
    ],

    "sketchy_2": [
        "bat",
        "cabin",
        "cow",
        "dolphin",
        "door",
        "giraffe",
        "helicopter",
        "mouse",
        "pear",
        "raccoon",
        "rhinoceros",
        "saw",
        "scissors",
        "seagull",
        "skyscraper",
        "songbird",
        "sword",
        "tree",
        "wheelchair",
        "windmill",
        "window",
    ],

    "quickdraw": [
        "bat",
        "cow",
        "dolphin",
        "door",
        "giraffe",
        "helicopter",
        "mouse",
        "raccoon",
        "rhinoceros",
        "saw",
        "scissors",
        "skyscraper",
        "tree",
        "windmill",
        "feather",
        "campfire",
        "palm_tree",
        "fire_hydrant",
        "bread",
        "beach",
        "megaphone",
        "cactus",
        "zebra",
        "tiger",
        "shark",
        "frog",
        "banana",
        "cake",
        "hamburger",
        "fan"
    ],

    "tuberlin": [
        "banana",
        "bus",
        "tractor",
        "suitcase",
        "streetlight",
        "telephone",
        "bottle opener",
        "canoe",
        "fan",
        "teacup",
        "penguin",
        "laptop",
        "shoe",
        "lighter",
        "hot air balloon",
        "pizza",
        "brain",
        "ant",
        "t-shirt",
        "trombone",
        "windmill",
        "snowboard",
        "table",
        "rollerblades",
        "parachute",
        "space shuttle",
        "bridge",
        "frying-pan",
        "bread",
        "horse",
    ]

}
